import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Card from './componente/card.js'
import NavBar from './componente/navbar.js'


const inter = Inter({ subsets: ['latin'] })

const myData = [ {name:"Pencilvester", image:"https://rickandmortyapi.com/api/character/avatar/259.jpeg"  },
                 {name:"Orthodox Jew", image:"https://rickandmortyapi.com/api/character/avatar/255.jpeg"  },
                 {name:"No se", image:"https://rickandmortyapi.com/api/character/avatar/251.jpeg"  }
               ]



export default function Home() {

  fetch("data.json")
                .then(response => console.log("Se cumplio la promesa: " + response))
                .catch( reason => console.log("NO cumplio la promesa: " + reason))


  return (
    <>
      <Head>
        <title>Felicidades Arantza</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar></NavBar>

      {
          myData.map( element =>(
            <Card img={element.image} name={element.name} ></Card>
          ))
        }

      </main>
    </>
  )
}
